import type { Metadata } from 'next'
import './globals.css'
import Navbar from './components/Navbar'
import { Josefin_Sans } from "next/font/google";
import Heading from './utils/Heading';
import { ThemeProvider } from './utils/theme-provider';


const inter = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Heading />
      <body className={`dark:bg-stone-900 ${inter.className}`} >
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          <main>{children}</main>
        </ThemeProvider>
        </body>
    </html>
  )
}
